os: linux
dist: bionic
language: minimal

env:
  - DEBIAN_FRONTEND: noninteractive

before_install:
  - sudo apt-get update
  - sudo apt-get -qqy install debootstrap kpartx qemu-system-x86 qemu-utils python3-pip
  - sudo pip3 --no-cache-dir install diskimage-builder

script:
  - sudo /bin/bash travisci/build.sh

after_success:
  - ls -lh /tmp/devstack.cmp.img
  - /bin/bash ffsend.sh
