os: linux
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get -qqy install debootstrap kpartx qemu-system-x86 qemu-utils python3-pip
  - sudo pip3 install diskimage-builder

script:
  - sudo /bin/bash travisci/build-debian.sh

after_success:
  - ls -lh /tmp/devstack.cmp.img
  - sudo /bin/bash travisci/ffsend.sh /tmp/devstack.cmp.img
