name: GitHub Actions

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install python3-diskimage-builder
        run: sudo pip3 install diskimage-builder

      - name: Install required packages
        run: sudo apt update && sudo apt-get install -qqy debootstrap kpartx qemu-system-x86

      - name: Build devstack.cmp.img
        run: sudo /bin/bash githubci/build.sh

      - name: ls
        run: ls -lh /tmp/devstack.cmp.img

      - name: Push to Firefox Send
        run: /bin/bash ffsend.sh /tmp/devstack.cmp.img
        env:
          FFSEND_BASIC_AUTH: ${{ secrets.FFSEND_BASIC_AUTH }}
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
