name: Build DevStack All-In-One Single VM Image

on:
  push:
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build devstack-vm.img
        run: sudo /bin/bash githubci/vm.sh

      - name: Push
        run: /bin/bash transfer.sh /dev/shm/devstack-vm.img
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
